# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-25 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qqgroup',
            name='members',
        ),
        migrations.DeleteModel(
            name='QQGroup',
        ),
    ]
