# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-25 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qq', '0002_auto_20160725_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u7fa4\u540d')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u6210\u5458')),
            ],
            options={
                'verbose_name': '\u7fa4\u7ec4',
            },
        ),
    ]
