# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qq', '0003_qqgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qqgroup',
            options={'verbose_name': '\u7fa4\u7ec4', 'verbose_name_plural': '\u7fa4\u7ec4'},
        ),
    ]
