# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 02:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u5e7f\u544a\u6807\u9898')),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='\u5e7f\u544a\u7b80\u4ecb')),
                ('image_url', models.ImageField(blank=True, upload_to='ad/%Y/%m', verbose_name='\u56fe\u7247\u5730\u5740')),
                ('callback_url', models.URLField(blank=True, max_length=255, verbose_name='\u5e7f\u544a\u94fe\u63a5')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('index', models.IntegerField(default=999, verbose_name='\u4ece\u5c0f\u5230\u5927\u6392\u5e8f')),
            ],
            options={
                'ordering': ['index', '-date_publish'],
                'verbose_name': '\u5e7f\u544a',
                'verbose_name_plural': '\u5e7f\u544a',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='\u7b80\u4ecb')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('click_count', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u91cf')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='\u662f\u5426\u63a8\u8350')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-date_publish', 'id'],
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u7c7b\u540d')),
                ('index', models.IntegerField(default=999, verbose_name='\u4ece\u5c0f\u5230\u5927\u6392\u5e8f')),
            ],
            options={
                'ordering': ['index'],
                'verbose_name': '\u6587\u7ae0\u5206\u7c7b',
                'verbose_name_plural': '\u6587\u7ae0\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='\u6587\u7ae0')),
                ('pid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='\u7236\u7ea7\u8bc4\u8bba')),
            ],
            options={
                'ordering': ['-date_publish', 'id'],
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u94fe\u63a5\u6807\u9898')),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='\u94fe\u63a5\u7b80\u4ecb')),
                ('callback_url', models.URLField(blank=True, max_length=255, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('index', models.IntegerField(default=999, verbose_name='\u4ece\u5c0f\u5230\u5927\u6392\u5e8f')),
            ],
            options={
                'ordering': ['index', '-date_publish'],
                'verbose_name': '\u53cb\u94fe',
                'verbose_name_plural': '\u53cb\u94fe',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u6807\u7b7e\u540d')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default.jpg', upload_to='avatar/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='\u6587\u7ae0\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
