# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160713_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_friend_+', to=settings.AUTH_USER_MODEL, verbose_name='\u670b\u53cb'),
        ),
    ]
